#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: brewrap VERSION"
  exit 1;
fi

version=$1

if [ ! -d versions ]; then
	mkdir versions
fi

tar_file_name=versions/v$version.tar.gz

tar --exclude='./.git' --exclude='./README.md' --exclude='./versions' -zcvf $tar_file_name .
